version: "3.9"

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1-2
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./webapp1:/usr/share/nginx/html
    networks:
      - mi_red

  nginx2:
    image: nginx:latest
    container_name: nginx2-2
    ports:
      - 81:80
    volumes:
      - ./webapp2:/usr/share/nginx/html
    networks:
      mi_red:
        aliases:
          - agencia.com
          - miblog.com
          - misnoticias.com
          - agencia.es
          - miblog.es
          - misnoticias.es

networks:
  mi_red:

volumes:
  webapp1:
  webapp2: